Update generate_release.yml

diff --git a/.github/workflows/generate_release.yml b/.github/workflows/generate_release.yml
--- a/.github/workflows/generate_release.yml
+++ b/.github/workflows/generate_release.yml
@@ -33,35 +33,13 @@ jobs:
           elif [ "$branch_prefix" == "patch" ]; then
             incremental_type=PATCH
           else
-            incremental_type=UNKNOWN
+            incremental_type=NONE
           fi
           echo "INCREMENTAL_TYPE=$incremental_type" >> $GITHUB_ENV
-      
-      # Exceptions skip release generation process
-      - name: Error handling for unknown branches
-        if: ${{ env.INCREMENTAL_TYPE == 'UNKNOWN' }}
-        run: |
-          case "$branch_prefix" in
-            # Exceptions for wrong branch name
-            "gh-action")
-              skip_gen_release=true
-              ;;
-            # Everything else is wrong
-            *)
-              skip_gen_release=false
-              ;;
-          esac
-          
-          if [ "$skip_gen_release" == "false" ] ; then
-            echo "::error ::Wrong Branch Name"
-            exit 1
-          else
-            echo "::notice ::Skipping Release Generation"
-            exit 0
-          fi
 
       - name: Check release existence
         id: check_release
+        if: ${{ env.INCREMENTAL_TYPE != 'NONE' }}
         env:
           GITHUB_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
         run: |
@@ -83,7 +61,8 @@ jobs:
               echo "exist=false" >> $GITHUB_OUTPUT
             fi
           else
-            echo "::error file=main.yml::Invalid access to the requestesd repository"
+            echo "::error Invalid access to the requestesd repository"
+            exit 1
           fi
 
       #https://github.com/marketplace/actions/get-latest-release
@@ -98,6 +77,7 @@ jobs:
           token: ${{ secrets.GIT_ACCESS_TOKEN }}
 
       - name: Set Current Release tag name, prerelease version
+        if: ${{ env.INCREMENTAL_TYPE != 'NONE' }}
         run: |
           # Remove 'v' from tag name
           CURRENT_TAG_NAME=$(echo "${{ steps.get_current_release.outputs.release }}" | cut -d'-' -f1 | sed 's/^v//')
@@ -110,12 +90,14 @@ jobs:
       #https://github.com/marketplace/actions/update-semantic-version
       - name: Set new semantic version
         id: new_version
+        if: ${{ env.INCREMENTAL_TYPE != 'NONE' }}
         uses: cookbenjamin/update-version@v1.0.1
         with:
           current-version: '${{ env.CURRENT_TAG_NAME }}' #X.Y.Z
           increment-version-fragment: '${{ env.INCREMENTAL_TYPE }}'
 
       - name: Set current release version
+        if: ${{ env.INCREMENTAL_TYPE != 'NONE' }}
         run: |
           echo "CURRENT_MAJOR_VERSION=$(echo ${{ env.CURRENT_TAG_NAME }} | cut -d'.' -f1)" >> $GITHUB_ENV
 
@@ -128,6 +110,7 @@ jobs:
           branch: 'refs/heads/release-stable-${{ env.CURRENT_MAJOR_VERSION }}'
 
       - name: Create release
+        if: ${{ env.INCREMENTAL_TYPE != 'NONE' }}
         uses: actions/create-release@v1
         env:
             GITHUB_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
