Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -45,19 +45,27 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
         run: |
-          releases=$(curl -L \
-            -H "Accept: application/vnd.github+json" \
-            -H "Authorization: Bearer $GITHUB_TOKEN" \
-            -H "X-GitHub-Api-Version: 2022-11-28" \
-            https://api.github.com/repos/${{ github.repository }}/releases)
-          echo $releases
-          if [ "$(echo "$releases" | jq '. | length')" -gt 0 ]; then
-            echo "Releases exist"
-            echo "exist=true" >> $GITHUB_OUTPUT
+          curl -L -f -o ./releases.out \
+               -H "Accept: application/vnd.github+json" \
+               -H "Authorization: Bearer $GITHUB_TOKEN" \
+               -H "X-GitHub-Api-Version: 2022-11-28" \
+               https://api.github.com/repos/${{ github.repository }}/releases)
+          
+          return_code=$?
+          
+          if [ $return_code -eq 0 ]; then
+            reply=$( cat ./releases.out )
+            if [ "$(echo "$reply" | jq '. | length')" -gt 0 ] ; then
+              echo "Releases exist"
+              echo "exist=true" >> $GITHUB_OUTPUT
+            else
+              echo "No releases found"
+              echo "exist=false" >> $GITHUB_OUTPUT
+            fi
           else
-            echo "No releases found"
-            echo "exist=false" >> $GITHUB_OUTPUT
+            echo "::error file=main.yml::Invalid access to the requestesd repository"
           fi
+
       #https://github.com/marketplace/actions/get-latest-release
       - name: Get Current Release
         if: ${{ steps.check_release.outputs.exist == 'true' }}
